version: '2'

services:
  cattle:
    image: devopsopen/docker-rancher
    ports:
      - "8090:8080"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    restart: always
